const permissions = {
  principal: {
    students: ['read', 'write', 'delete'],
    admissions: ['read', 'write', 'delete'],
    staff: ['read', 'write', 'delete'],
    academics: ['read', 'write', 'delete'],
    attendance: ['read', 'write', 'delete'],
    exams: ['read', 'write', 'delete'],
    finance: ['read', 'write', 'delete'],
    hostel: ['read', 'write', 'delete'],
    health: ['read', 'write', 'delete'],
    hr_payroll: ['read', 'write', 'delete'],
    library: ['read', 'write', 'delete'],
    transport: ['read', 'write', 'delete'],
    reports: ['read', 'write', 'delete'],
    system_settings: ['read', 'write', 'delete'],
    audit_logs: ['read'],
  },
  vice_principal: {
    students: ['read', 'write', 'delete'],
    admissions: ['read', 'write', 'delete'],
    staff: ['read', 'write', 'delete'],
    academics: ['read', 'write', 'delete'],
    attendance: ['read', 'write', 'delete'],
    exams: ['read', 'write', 'delete'],
    finance: ['read', 'write', 'delete'],
    hostel: ['read', 'write', 'delete'],
    health: ['read', 'write', 'delete'],
    hr_payroll: ['read', 'write', 'delete'],
    library: ['read', 'write', 'delete'],
    transport: ['read', 'write', 'delete'],
    reports: ['read', 'write', 'delete'],
    system_settings: ['read', 'write', 'delete'],
    audit_logs: ['read'],
  },
  academic_coordinator: {
    students: ['read'],
    academics: ['read', 'write', 'delete'],
    attendance: ['read', 'write', 'delete'],
    exams: ['read'],
    reports: ['read'],
  },
  class_teacher: {
    students: ['read'],
    academics: ['read', 'write'],
    attendance: ['read', 'write'],
    exams: ['read'],
    hostel: ['read'],
    reports: ['read'],
  },
  subject_teacher: {
    academics: ['read', 'write'],
    attendance: ['read', 'write'],
    exams: ['read', 'write'],
  },
  exam_controller: {
    students: ['read'],
    exams: ['read', 'write', 'delete'],
    finance: ['read'],
    reports: ['read'],
  },
  accounts_officer: {
    students: ['read'],
    staff: ['read'],
    exams: ['read'],
    finance: ['read', 'write', 'delete'],
    reports: ['read'],
  },
  cashier: {
    finance: ['read', 'write'],
  },
  hr_manager: {
    students: ['read'],
    staff: ['read', 'write', 'delete'],
    attendance: ['read', 'write'],
    finance: ['read'],
    hr_payroll: ['read', 'write', 'delete'],
    reports: ['read'],
  },
  hostel_warden: {
    students: ['read'],
    staff: ['read'],
    attendance: ['read', 'write'],
    finance: ['read'],
    hostel: ['read', 'write', 'delete'],
    health: ['read'],
    reports: ['read'],
  },
  asst_hostel_warden: {
    students: ['read'],
    attendance: ['read', 'write'],
    hostel: ['read', 'write'],
  },
  medical_officer: {
    students: ['read'],
    health: ['read', 'write', 'delete'],
    reports: ['read'],
  },
  admissions_officer: {
    students: ['read', 'write'],
    admissions: ['read', 'write', 'delete'],
    finance: ['read'],
    reports: ['read'],
  },
  transport_manager: {
    students: ['read'],
    transport: ['read', 'write', 'delete'],
    finance: ['read'],
    reports: ['read'],
  },
  librarian: {
    students: ['read'],
    finance: ['read'],
    library: ['read', 'write', 'delete'],
    reports: ['read'],
  },
  it_admin: {
    students: ['read'],
    staff: ['read'],
    academics: ['read'],
    exams: ['read'],
    finance: ['read'],
    hostel: ['read'],
    health: ['read'],
    hr_payroll: ['read'],
    library: ['read'],
    transport: ['read'],
    reports: ['read'],
    system_settings: ['read', 'write', 'delete'],
    audit_logs: ['read'],
  },
  receptionist: {},
  security_supervisor: {},
  student: {
    students: ['read'],
    academics: ['read'],
    attendance: ['read'],
    exams: ['read'],
    finance: ['read'],
    hostel: ['read', 'write'],
    library: ['read'],
    transport: ['read'],
    health: ['read'],
    reports: ['read'],
  },
  parent: {
    students: ['read'],
    academics: ['read'],
    attendance: ['read'],
    exams: ['read'],
    finance: ['read'],
    hostel: ['read'],
    library: ['read'],
    transport: ['read'],
    health: ['read'],
    reports: ['read'],
  },
};

module.exports = permissions;
