export const navigationItems = [
  { key: 'overview', label: 'Overview', icon: 'LayoutDashboard', path: '/dashboard/overview', roles: ['principal', 'vice_principal'] },
  { key: 'students', label: 'Students', icon: 'GraduationCap', path: '/dashboard/students', roles: ['principal', 'vice_principal'] },
  { key: 'admissions', label: 'Admissions', icon: 'UserPlus', path: '/dashboard/admissions', roles: ['principal', 'vice_principal', 'admissions_officer'] },
  { key: 'academics', label: 'Academics', icon: 'BookOpen', path: '/dashboard/academics', roles: ['principal', 'vice_principal', 'academic_coordinator'] },
  { key: 'attendance', label: 'Attendance', icon: 'ClipboardCheck', path: '/dashboard/attendance', roles: ['principal', 'vice_principal', 'academic_coordinator', 'class_teacher', 'hostel_warden', 'asst_hostel_warden'] },
  { key: 'timetable', label: 'Timetable', icon: 'Calendar', path: '/dashboard/timetable', roles: ['principal', 'vice_principal', 'academic_coordinator', 'class_teacher'] },
  { key: 'exams', label: 'Exams', icon: 'FileText', path: '/dashboard/exams', roles: ['principal', 'vice_principal', 'academic_coordinator', 'exam_controller', 'class_teacher'] },
  { key: 'marks', label: 'Marks Entry', icon: 'PenLine', path: '/dashboard/marks', roles: ['class_teacher', 'subject_teacher'] },
  { key: 'finance', label: 'Finance', icon: 'IndianRupee', path: '/dashboard/finance', roles: ['principal', 'vice_principal', 'accounts_officer'] },
  { key: 'fee-collection', label: 'Fee Collection', icon: 'Wallet', path: '/dashboard/fee-collection', roles: ['cashier', 'accounts_officer'] },
  { key: 'hostel', label: 'Hostel', icon: 'Building2', path: '/dashboard/hostel', roles: ['principal', 'vice_principal', 'hostel_warden', 'asst_hostel_warden'] },
  { key: 'hr', label: 'HR & Staff', icon: 'Users', path: '/dashboard/hr', roles: ['principal', 'vice_principal', 'hr_manager'] },
  { key: 'library', label: 'Library', icon: 'Library', path: '/dashboard/library', roles: ['principal', 'vice_principal', 'librarian'] },
  { key: 'transport', label: 'Transport', icon: 'Bus', path: '/dashboard/transport', roles: ['principal', 'vice_principal', 'transport_manager'] },
  { key: 'health', label: 'Health', icon: 'HeartPulse', path: '/dashboard/health', roles: ['principal', 'vice_principal', 'medical_officer'] },
  { key: 'reports', label: 'Reports', icon: 'BarChart3', path: '/dashboard/reports', roles: ['principal', 'vice_principal', 'academic_coordinator', 'exam_controller', 'accounts_officer', 'hr_manager', 'hostel_warden', 'medical_officer', 'admissions_officer', 'transport_manager', 'librarian', 'it_admin', 'class_teacher'] },
  { key: 'staff-portal', label: 'Staff Portal', icon: 'Briefcase', path: '/dashboard/staff-portal', roles: ['principal', 'vice_principal', 'academic_coordinator', 'class_teacher', 'subject_teacher', 'exam_controller', 'accounts_officer', 'cashier', 'hr_manager', 'hostel_warden', 'asst_hostel_warden', 'medical_officer', 'admissions_officer', 'transport_manager', 'librarian', 'it_admin', 'receptionist', 'security_supervisor'] },
  { key: 'settings', label: 'Settings', icon: 'Settings', path: '/dashboard/settings', roles: ['principal', 'vice_principal', 'it_admin'] },
  { key: 'student-portal', label: 'Student Portal', icon: 'User', path: '/dashboard/student', roles: ['student'] },
  { key: 'parent-portal', label: 'Parent Portal', icon: 'Users', path: '/dashboard/student', roles: ['parent'] },
];

export const moduleColors = {
  admissions: '#7C3AED',
  academics: '#2563EB',
  exams: '#D97706',
  finance: '#16A34A',
  hostel: '#0D9488',
  hr: '#EA580C',
  library: '#9333EA',
  transport: '#0891B2',
  health: '#DC2626',
  reports: '#4F46E5',
  student: '#EC4899',
};
